export const FACTIONS = [
  {
    id: "frost",
    name: "Frostborn",
    role: "Tactical Scout · Recon",
    world: "Hothar-IX",
    blurb:
      "Built to survive brutal environmental extremes and read a collapsing world before it turns on you.",
    trait: "+15% Storm-Dimension Vision",
    lore: "Forged on a dying ice-giant, Frostborn operatives learned to read collapsing storm-dimensions before they could walk. Their neural architecture processes environmental data in parallel — you don't outrun a blizzard, you predict it.",
    playstyle: "Best for: Zone control · Intel dominance · Outlasting. Hard to kill in open environments.",
    danger: "MODERATE",
    color: "#5fd6f5",
    glow: "#9fe9ff",
    pos: [-3.3, 1.5, -0.6],
    radius: 0.95,
    spin: 0.16,
  },
  {
    id: "shadow",
    name: "Shadowcat",
    role: "Infiltrator · Stealth",
    world: "Umbra Reach",
    blurb:
      "Ghost-like speed and high-tier looting bonuses. In and out before a rival crew knows you came.",
    trait: "+20% Rare-loot Detection",
    lore: "Umbra Reach bred killers who leave no footprint. Shadowcats trained in gravity-null chambers — their nervous systems rewired to treat silence as a weapon and light as a liability. Every raid is a controlled disappearance.",
    playstyle: "Best for: High-risk extraction · Solo raiding · First in, last out. Punishing in the right hands.",
    danger: "HIGH",
    color: "#9d6bff",
    glow: "#c4a6ff",
    pos: [-1.9, -1.9, 1.3],
    radius: 0.72,
    spin: 0.24,
  },
  {
    id: "talon",
    name: "Talon",
    role: "Marksman · Tracking",
    world: "Aerie Prime",
    blurb:
      "Long-range precision and target tracking. Hunts threats from the shadows before they close in.",
    trait: "+18% Mark & Track Range",
    lore: "Aerie Prime's stratospheric jungles demanded precision or death. Talons catalogue threats before engaging — their optics lock, their hands steady, and the trigger only pulls once. Distance is their ally; panic is their enemy's.",
    playstyle: "Best for: Long-range dominance · Threat marking · Holding perimeters. Devastating at range.",
    danger: "MODERATE",
    color: "#e8c98a",
    glow: "#f6e4ba",
    pos: [3.5, 0.7, 0.4],
    radius: 1.15,
    spin: 0.12,
  },
  {
    id: "vulpine",
    name: "Vulpine",
    role: "Engineer · Crafting",
    world: "Cinder Hollow",
    blurb:
      "Resourceful fighter and negotiator who turns raw scrap into advanced gear faster than anyone.",
    trait: "Deconstructs scrap 20% faster",
    lore: "Cinder Hollow survivors never had supply lines. Vulpines learned to strip a reactor core in under three minutes and build a weapon from the wreckage. Every extraction is a harvest. Every corpse is a parts list.",
    playstyle: "Best for: Gear farming · Crafting loops · Resource-rich zones. High ceiling, high chaos.",
    danger: "EXTREME",
    color: "#ff7a2e",
    glow: "#ffb27a",
    pos: [2.5, -1.7, -1.1],
    radius: 1.0,
    spin: 0.2,
  },
];

export const byId = (id) => FACTIONS.find((f) => f.id === id) || null;
